### ISSUE TITLE
Import DXF file from local

### ISSUE THREAD

**Issue by Hazii-197** [xibyte/jsketcher#92] opened 2020-01-02 11:54 UTC
Firstly, This application is awesome :).
 I need some customization in this application like import-export and some minor changes.
is the import feature is the part of the application?
at issue number 67,  mentions that we are working on implementing this feature.. any progress???

Thanks

**Comment by mmiscool** [comment] 2020-03-25 06:29
Duplicate of issue 67. 
https://github.com/xibyte/jsketcher/issues/67

**Closed by mmiscool** 2020-03-25 06:29 UTC
Labels: duplicate, enhancement
